stringArray = input("Enter string: ")
stringArray = stringArray.split(",")
stringArray = sorted(list(map(int, stringArray)))
print("Max:", max(stringArray))
print("Min:", min(stringArray))
print("Sum:", sum(stringArray[1:-1]))